[project]
name = "bmi-calculator-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.11.2",
    "streamlit>=1.44.0",
]
